# Site settings
title: "eddieantonio/blog"
email: easantos@ualberta.ca
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on software, linguistics, and jazz fusion.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.eddieantonio.ca" # the base hostname & protocol for your site
twitter_username: _eddieantonio
github_username:  eddieantonio

# Build settings
markdown: kramdown
drafts: no
permalink: pretty
highlighter: rouge

# Defaults sets everything to a post, with me as the author and comments
# enabled.
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "eddieantonio"
      comments: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: post

# All the gems that GitHub pages supports.
plugins:
 - jekyll-mentions
 - jemoji # Most important!
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-feed
