# Site settings
title: "eddieantonio/blog"
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on software, linguistics, and jazz fusion.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://www.eddieantonio.ca" # the base hostname & protocol for your site

author:
  name: &name Eddie Antonio Santos
  email: easantos@ualberta.ca
  uri: https://www.eddieantonio.ca/
  twitter: &twitter _eddieantonio
  github: eddieantonio
  linkedin: eddieantonio

twitter:
  username: *twitter
  card: summary

social:
  name: *name
  links:
    - https://twitter.com/_eddieantonio
    - https://www.linkedin.com/in/eddieantonio/
    - https://github.com/eddieantonio
    - https://keybase.io/eddieantonio

# Default locale, if not specified.
lang: en_CA

# Build settings
markdown: kramdown
drafts: no
permalink: pretty
highlighter: rouge

# Defaults sets everything to a post, with comments enabled.
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true

# All the gems that GitHub pages supports.
plugins:
 - jekyll-mentions
 - jemoji # Most important!
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-feed
 - jekyll-seo-tag

exclude:
  - README.md
